// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlc

import (
	"database/sql"
)

type MicrohookActionSnapshot struct {
	RunID              string
	Description        string
	Mode               string
	CommandJson        []byte
	ShellCommand       string
	Cwd                string
	TimeoutNanoseconds int64
	EnvJson            []byte
	ConcurrencyPolicy  string
	MaxOutputBytes     int64
	Enabled            int64
}

type MicrohookMetadatum struct {
	Key   string
	Value string
}

type MicrohookRun struct {
	ID                  string
	ActionName          string
	Status              string
	ExitCode            sql.NullInt64
	CreatedAtUnixNano   int64
	StartedAtUnixNano   sql.NullInt64
	FinishedAtUnixNano  sql.NullInt64
	TimedOut            int64
	RequestMetadataJson []byte
	StdoutTail          string
	StderrTail          string
	ErrorSummary        string
}

type MicrohookRunRecord struct {
	ID                  string
	ActionName          string
	Status              string
	ExitCode            sql.NullInt64
	CreatedAtUnixNano   int64
	StartedAtUnixNano   sql.NullInt64
	FinishedAtUnixNano  sql.NullInt64
	TimedOut            int64
	RequestMetadataJson []byte
	StdoutTail          string
	StderrTail          string
	ErrorSummary        string
	Description         string
	Mode                string
	CommandJson         []byte
	ShellCommand        string
	Cwd                 string
	TimeoutNanoseconds  int64
	EnvJson             []byte
	ConcurrencyPolicy   string
	MaxOutputBytes      int64
	Enabled             int64
}
