// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: storage_queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createActionSnapshot = `-- name: CreateActionSnapshot :exec
INSERT INTO microhook_action_snapshots (
    run_id,
    description,
    mode,
    command_json,
    shell_command,
    cwd,
    timeout_nanoseconds,
    env_json,
    concurrency_policy,
    max_output_bytes,
    enabled
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11
)
`

type CreateActionSnapshotParams struct {
	RunID              string
	Description        string
	Mode               string
	CommandJson        []byte
	ShellCommand       string
	Cwd                string
	TimeoutNanoseconds int64
	EnvJson            []byte
	ConcurrencyPolicy  string
	MaxOutputBytes     int64
	Enabled            int64
}

func (q *Queries) CreateActionSnapshot(ctx context.Context, arg CreateActionSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, createActionSnapshot,
		arg.RunID,
		arg.Description,
		arg.Mode,
		arg.CommandJson,
		arg.ShellCommand,
		arg.Cwd,
		arg.TimeoutNanoseconds,
		arg.EnvJson,
		arg.ConcurrencyPolicy,
		arg.MaxOutputBytes,
		arg.Enabled,
	)
	return err
}

const createRun = `-- name: CreateRun :exec
INSERT INTO microhook_runs (
    id,
    action_name,
    status,
    created_at_unix_nano,
    started_at_unix_nano,
    timed_out,
    request_metadata_json,
    stdout_tail,
    stderr_tail,
    error_summary
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10
)
`

type CreateRunParams struct {
	ID                  string
	ActionName          string
	Status              string
	CreatedAtUnixNano   int64
	StartedAtUnixNano   sql.NullInt64
	TimedOut            int64
	RequestMetadataJson []byte
	StdoutTail          string
	StderrTail          string
	ErrorSummary        string
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.ExecContext(ctx, createRun,
		arg.ID,
		arg.ActionName,
		arg.Status,
		arg.CreatedAtUnixNano,
		arg.StartedAtUnixNano,
		arg.TimedOut,
		arg.RequestMetadataJson,
		arg.StdoutTail,
		arg.StderrTail,
		arg.ErrorSummary,
	)
	return err
}

const deleteRunsOlderThan = `-- name: DeleteRunsOlderThan :execrows
DELETE FROM microhook_runs
WHERE id IN (
    SELECT id
    FROM microhook_runs
    WHERE microhook_runs.status <> ?1
      AND microhook_runs.created_at_unix_nano < ?2
)
`

type DeleteRunsOlderThanParams struct {
	ExcludedStatus        string
	CreatedBeforeUnixNano int64
}

func (q *Queries) DeleteRunsOlderThan(ctx context.Context, arg DeleteRunsOlderThanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRunsOlderThan, arg.ExcludedStatus, arg.CreatedBeforeUnixNano)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRunsOverflow = `-- name: DeleteRunsOverflow :execrows
DELETE FROM microhook_runs
WHERE id IN (
    SELECT id
    FROM microhook_runs
    WHERE microhook_runs.status <> ?1
    ORDER BY microhook_runs.created_at_unix_nano DESC, microhook_runs.id DESC
    LIMIT -1 OFFSET ?2
)
`

type DeleteRunsOverflowParams struct {
	ExcludedStatus string
	MaxRuns        int64
}

func (q *Queries) DeleteRunsOverflow(ctx context.Context, arg DeleteRunsOverflowParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRunsOverflow, arg.ExcludedStatus, arg.MaxRuns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMetadata = `-- name: GetMetadata :one
SELECT value
FROM microhook_metadata
WHERE key = ?1
LIMIT 1
`

func (q *Queries) GetMetadata(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMetadata, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getRun = `-- name: GetRun :one
SELECT id, action_name, status, exit_code, created_at_unix_nano, started_at_unix_nano, finished_at_unix_nano, timed_out, request_metadata_json, stdout_tail, stderr_tail, error_summary, description, mode, command_json, shell_command, cwd, timeout_nanoseconds, env_json, concurrency_policy, max_output_bytes, enabled
FROM microhook_run_records
WHERE id = ?1
LIMIT 1
`

func (q *Queries) GetRun(ctx context.Context, runID string) (MicrohookRunRecord, error) {
	row := q.db.QueryRowContext(ctx, getRun, runID)
	var i MicrohookRunRecord
	err := row.Scan(
		&i.ID,
		&i.ActionName,
		&i.Status,
		&i.ExitCode,
		&i.CreatedAtUnixNano,
		&i.StartedAtUnixNano,
		&i.FinishedAtUnixNano,
		&i.TimedOut,
		&i.RequestMetadataJson,
		&i.StdoutTail,
		&i.StderrTail,
		&i.ErrorSummary,
		&i.Description,
		&i.Mode,
		&i.CommandJson,
		&i.ShellCommand,
		&i.Cwd,
		&i.TimeoutNanoseconds,
		&i.EnvJson,
		&i.ConcurrencyPolicy,
		&i.MaxOutputBytes,
		&i.Enabled,
	)
	return i, err
}

const listRuns = `-- name: ListRuns :many
SELECT id, action_name, status, exit_code, created_at_unix_nano, started_at_unix_nano, finished_at_unix_nano, timed_out, request_metadata_json, stdout_tail, stderr_tail, error_summary, description, mode, command_json, shell_command, cwd, timeout_nanoseconds, env_json, concurrency_policy, max_output_bytes, enabled
FROM microhook_run_records
ORDER BY created_at_unix_nano DESC, id DESC
`

func (q *Queries) ListRuns(ctx context.Context) ([]MicrohookRunRecord, error) {
	rows, err := q.db.QueryContext(ctx, listRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MicrohookRunRecord
	for rows.Next() {
		var i MicrohookRunRecord
		if err := rows.Scan(
			&i.ID,
			&i.ActionName,
			&i.Status,
			&i.ExitCode,
			&i.CreatedAtUnixNano,
			&i.StartedAtUnixNano,
			&i.FinishedAtUnixNano,
			&i.TimedOut,
			&i.RequestMetadataJson,
			&i.StdoutTail,
			&i.StderrTail,
			&i.ErrorSummary,
			&i.Description,
			&i.Mode,
			&i.CommandJson,
			&i.ShellCommand,
			&i.Cwd,
			&i.TimeoutNanoseconds,
			&i.EnvJson,
			&i.ConcurrencyPolicy,
			&i.MaxOutputBytes,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByActionName = `-- name: ListRunsByActionName :many
SELECT id, action_name, status, exit_code, created_at_unix_nano, started_at_unix_nano, finished_at_unix_nano, timed_out, request_metadata_json, stdout_tail, stderr_tail, error_summary, description, mode, command_json, shell_command, cwd, timeout_nanoseconds, env_json, concurrency_policy, max_output_bytes, enabled
FROM microhook_run_records
WHERE action_name = ?1
ORDER BY created_at_unix_nano DESC, id DESC
`

func (q *Queries) ListRunsByActionName(ctx context.Context, filterActionName string) ([]MicrohookRunRecord, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByActionName, filterActionName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MicrohookRunRecord
	for rows.Next() {
		var i MicrohookRunRecord
		if err := rows.Scan(
			&i.ID,
			&i.ActionName,
			&i.Status,
			&i.ExitCode,
			&i.CreatedAtUnixNano,
			&i.StartedAtUnixNano,
			&i.FinishedAtUnixNano,
			&i.TimedOut,
			&i.RequestMetadataJson,
			&i.StdoutTail,
			&i.StderrTail,
			&i.ErrorSummary,
			&i.Description,
			&i.Mode,
			&i.CommandJson,
			&i.ShellCommand,
			&i.Cwd,
			&i.TimeoutNanoseconds,
			&i.EnvJson,
			&i.ConcurrencyPolicy,
			&i.MaxOutputBytes,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByActionNameAndStatus = `-- name: ListRunsByActionNameAndStatus :many
SELECT id, action_name, status, exit_code, created_at_unix_nano, started_at_unix_nano, finished_at_unix_nano, timed_out, request_metadata_json, stdout_tail, stderr_tail, error_summary, description, mode, command_json, shell_command, cwd, timeout_nanoseconds, env_json, concurrency_policy, max_output_bytes, enabled
FROM microhook_run_records
WHERE action_name = ?1
  AND status = ?2
ORDER BY created_at_unix_nano DESC, id DESC
`

type ListRunsByActionNameAndStatusParams struct {
	FilterActionName string
	FilterStatus     string
}

func (q *Queries) ListRunsByActionNameAndStatus(ctx context.Context, arg ListRunsByActionNameAndStatusParams) ([]MicrohookRunRecord, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByActionNameAndStatus, arg.FilterActionName, arg.FilterStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MicrohookRunRecord
	for rows.Next() {
		var i MicrohookRunRecord
		if err := rows.Scan(
			&i.ID,
			&i.ActionName,
			&i.Status,
			&i.ExitCode,
			&i.CreatedAtUnixNano,
			&i.StartedAtUnixNano,
			&i.FinishedAtUnixNano,
			&i.TimedOut,
			&i.RequestMetadataJson,
			&i.StdoutTail,
			&i.StderrTail,
			&i.ErrorSummary,
			&i.Description,
			&i.Mode,
			&i.CommandJson,
			&i.ShellCommand,
			&i.Cwd,
			&i.TimeoutNanoseconds,
			&i.EnvJson,
			&i.ConcurrencyPolicy,
			&i.MaxOutputBytes,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByStatus = `-- name: ListRunsByStatus :many
SELECT id, action_name, status, exit_code, created_at_unix_nano, started_at_unix_nano, finished_at_unix_nano, timed_out, request_metadata_json, stdout_tail, stderr_tail, error_summary, description, mode, command_json, shell_command, cwd, timeout_nanoseconds, env_json, concurrency_policy, max_output_bytes, enabled
FROM microhook_run_records
WHERE status = ?1
ORDER BY created_at_unix_nano DESC, id DESC
`

func (q *Queries) ListRunsByStatus(ctx context.Context, filterStatus string) ([]MicrohookRunRecord, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByStatus, filterStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MicrohookRunRecord
	for rows.Next() {
		var i MicrohookRunRecord
		if err := rows.Scan(
			&i.ID,
			&i.ActionName,
			&i.Status,
			&i.ExitCode,
			&i.CreatedAtUnixNano,
			&i.StartedAtUnixNano,
			&i.FinishedAtUnixNano,
			&i.TimedOut,
			&i.RequestMetadataJson,
			&i.StdoutTail,
			&i.StderrTail,
			&i.ErrorSummary,
			&i.Description,
			&i.Mode,
			&i.CommandJson,
			&i.ShellCommand,
			&i.Cwd,
			&i.TimeoutNanoseconds,
			&i.EnvJson,
			&i.ConcurrencyPolicy,
			&i.MaxOutputBytes,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMetadata = `-- name: SetMetadata :exec
INSERT INTO microhook_metadata (key, value)
VALUES (?1, ?2)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetMetadataParams struct {
	Key   string
	Value string
}

func (q *Queries) SetMetadata(ctx context.Context, arg SetMetadataParams) error {
	_, err := q.db.ExecContext(ctx, setMetadata, arg.Key, arg.Value)
	return err
}

const updateRun = `-- name: UpdateRun :execrows
UPDATE microhook_runs
SET
    status = ?1,
    exit_code = ?2,
    started_at_unix_nano = ?3,
    finished_at_unix_nano = ?4,
    timed_out = ?5,
    stdout_tail = ?6,
    stderr_tail = ?7,
    error_summary = ?8
WHERE id = ?9
`

type UpdateRunParams struct {
	Status             string
	ExitCode           sql.NullInt64
	StartedAtUnixNano  sql.NullInt64
	FinishedAtUnixNano sql.NullInt64
	TimedOut           int64
	StdoutTail         string
	StderrTail         string
	ErrorSummary       string
	ID                 string
}

func (q *Queries) UpdateRun(ctx context.Context, arg UpdateRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRun,
		arg.Status,
		arg.ExitCode,
		arg.StartedAtUnixNano,
		arg.FinishedAtUnixNano,
		arg.TimedOut,
		arg.StdoutTail,
		arg.StderrTail,
		arg.ErrorSummary,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
