// Package auth provides authentication and authorization services for Microhook.
package auth

import (
	"context"
	"crypto/sha256"
	"crypto/subtle"
	"errors"
	"net/http"
	"strings"

	"github.com/nicotsx/microhook/internal/auth/tokenformat"
	"github.com/nicotsx/microhook/internal/config"
)

var (
	ErrMissingBearerToken = errors.New("missing bearer token")
	ErrInvalidBearerToken = errors.New("invalid bearer token")
	ErrForbiddenAction    = errors.New("forbidden action")
)

type contextKey string

const identityContextKey contextKey = "auth.identity"

type Identity struct {
	name      string
	global    bool
	actionSet map[string]struct{}
}

func (i Identity) Name() string {
	return i.name
}

func (i Identity) IsGlobal() bool {
	return i.global
}

func (i Identity) AllowsAction(actionName string) bool {
	if i.global {
		return true
	}

	_, ok := i.actionSet[actionName]
	return ok
}

func ContextWithIdentity(ctx context.Context, identity Identity) context.Context {
	return context.WithValue(ctx, identityContextKey, identity)
}

func IdentityFromContext(ctx context.Context) (Identity, bool) {
	identity, ok := ctx.Value(identityContextKey).(Identity)
	return identity, ok
}

type Service struct {
	credentials []tokenCredential
}

type tokenCredential struct {
	identity Identity
	digest   [sha256.Size]byte
}

func New(cfg config.AuthConfig) (*Service, error) {
	credentials := make([]tokenCredential, 0, len(cfg.Tokens))
	for _, token := range cfg.Tokens {
		if token.Name == "" {
			return nil, errors.New("auth token name is required")
		}

		if token.Value == "" {
			return nil, errors.New("auth token value is required")
		}

		if err := tokenformat.Validate(token.Value); err != nil {
			return nil, errors.New("auth token value must be a valid Microhook token generated by `microhook generate-token`")
		}

		credentials = append(credentials, tokenCredential{
			identity: newIdentity(token),
			digest:   sha256.Sum256([]byte(token.Value)),
		})
	}

	return &Service{credentials: credentials}, nil
}

func (s *Service) AuthenticateRequest(request *http.Request) (Identity, error) {
	return s.AuthenticateHeader(request.Header.Get("Authorization"))
}

func (s *Service) AuthenticateHeader(header string) (Identity, error) {
	tokenValue, err := parseBearerToken(header)
	if err != nil {
		return Identity{}, err
	}

	return s.AuthenticateToken(tokenValue)
}

func (s *Service) AuthenticateToken(tokenValue string) (Identity, error) {
	if tokenValue == "" {
		return Identity{}, ErrInvalidBearerToken
	}

	providedDigest := sha256.Sum256([]byte(tokenValue))
	var matchedIdentity Identity
	matched := 0

	for _, credential := range s.credentials {
		equal := subtle.ConstantTimeCompare(providedDigest[:], credential.digest[:])
		if equal == 1 && matched == 0 {
			matchedIdentity = credential.identity
		}

		matched |= equal
	}

	if matched != 1 {
		return Identity{}, ErrInvalidBearerToken
	}

	return matchedIdentity, nil
}

func (s *Service) AuthorizeAction(identity Identity, actionName string) error {
	if identity.AllowsAction(strings.TrimSpace(actionName)) {
		return nil
	}

	return ErrForbiddenAction
}

func newIdentity(token config.Token) Identity {
	identity := Identity{
		name:   token.Name,
		global: token.IsGlobal(),
	}

	if len(token.Actions) == 0 {
		return identity
	}

	identity.actionSet = make(map[string]struct{}, len(token.Actions))
	for _, actionName := range token.Actions {
		identity.actionSet[actionName] = struct{}{}
	}

	return identity
}

func parseBearerToken(header string) (string, error) {
	parts := strings.Fields(header)
	if len(parts) == 0 {
		return "", ErrMissingBearerToken
	}

	if len(parts) != 2 || !strings.EqualFold(parts[0], "Bearer") || parts[1] == "" {
		return "", ErrInvalidBearerToken
	}

	return parts[1], nil
}
